### PR TITLE
allow to execute one test multiple times with different parameters

### PR DESCRIPTION
**Pull request by PetrDlouhy**
I wanted to perform the `check_cache` test on all of my caches so I modified the code to allow set/array in `ALIVE_CHECKS` settings.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@ipmb Could you please check this PR?

**Comment by ipmb** [comment]
I think the list of tuples format should be the default. We can keep `dict` support as a legacy/deprecated option.

**Comment by PetrDlouhy** [comment]
@ipmb Thanks for the comment. I have transformed the code, so that list of tuples is default. Dict now throws deprecated warning.

I have also added test for the old behavior. I had to move `ALIVE_CHECKS` variable to the function, otherwise the `override_settings` would not work.

All tests should pass when you pull #14

**Comment by PetrDlouhy** [comment]
@dchukhin Would you please look at this and #13 too?

**Comment by PetrDlouhy** [comment]
@ipmb Is everything OK with this PR or should I make some more effort?

**Comment by ipmb** [comment]
It's all good. I hope we can merge it soon... just doing some housekeeping to make this easier in the future.

**Review by dchukhin — APPROVED** [review]
Looks good to me.
Thanks for the contribution @PetrDlouhy!

**Pull request merged**
